"""Inicio

Revision ID: 083a4b440e3c
Revises: 
Create Date: 2025-11-26 01:56:13.455453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083a4b440e3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('cajero', sa.String(length=100), nullable=True),
    sa.Column('fondo_inicial', sa.Float(), nullable=True),
    sa.Column('ventas_efectivo', sa.Float(), nullable=True),
    sa.Column('ventas_tarjeta', sa.Float(), nullable=True),
    sa.Column('gastos', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('corte')
    # ### end Alembic commands ###
